						<!-- start: Photo Stream -->
						<div class="span3">
						
							<h3>Photo Stream</h3>
							<div class="flickr-widget">
								<script type="text/javascript" src="./js/badge_code_v2.gne"></script>
								<div class="flickr_badge_image" id="flickr_badge_image1">
									<a href="http://www.flickr.com/photos/29609591@N08/8637527812/">
										<img src="./img/8637527812_326926a060_s.jpg" alt="A photo on Flickr" title="Beech Tree Strathmore" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image2">
									<a href="http://www.flickr.com/photos/29609591@N08/8627629925/">
										<img src="./img/8627629925_0781c1fc87_s.jpg" alt="A photo on Flickr" title="Fowlis" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image3">
									<a href="http://www.flickr.com/photos/29609591@N08/8207432285/">
										<img src="./img/8207432285_b85b135b3e_s.jpg" alt="A photo on Flickr" title="Skotland" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image4">
									<a href="http://www.flickr.com/photos/29609591@N08/8188704520/">
										<img src="./img/8188704520_8d7b0a9536_s.jpg" alt="A photo on Flickr" title="Elgol From Tokavaig" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image5">
									<a href="http://www.flickr.com/photos/29609591@N08/8182862834/">
										<img src="./img/8182862834_45647ace5d_s.jpg" alt="A photo on Flickr" title="Buachaille Etive Mhor" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image6">
									<a href="http://www.flickr.com/photos/29609591@N08/8171984512/">
										<img src="./img/8171984512_d1a55efb7b_s.jpg" alt="A photo on Flickr" title="Forth Bridge" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image7">
									<a href="http://www.flickr.com/photos/29609591@N08/8164686559/">
										<img src="./img/8164686559_0e966d5797_s.jpg" alt="A photo on Flickr" title="Crannog Loch Tay" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image8">
									<a href="http://www.flickr.com/photos/29609591@N08/8145628896/">
										<img src="./img/8145628896_43d24df4f3_s.jpg" alt="A photo on Flickr" title="Eilean Sionnach Isleoransay" height="75" width="75">
									</a>
								</div>
								<div class="flickr_badge_image" id="flickr_badge_image9">
									<a href="http://www.flickr.com/photos/29609591@N08/8141689644/">
										<img src="./img/8141689644_0a063815a0_s.jpg" alt="A photo on Flickr" title="Staffin Bay Ray" height="75" width="75">
									</a>
								</div>
								<span style="position:absolute;left:-999em;top:-999em;visibility:hidden" class="flickr_badge_beacon"><img src="./img/p" width="0" height="0" alt=""></span>
								<div class="clear"></div>
							</div>
						
						</div>
						<!-- end: Photo Stream -->