
	<?php echo $this->navigation('navigation')->menu()
									          ->setMinDepth(0)
									          ->setMaxDepth(0)
									          ->setUlClass('nav'); ?>
<!-- 
<ul class="nav">
		<li class="active"><a href="<?= $this->serverUrl() ?>/">Home</a></li>
		<li><a href="<?= $this->serverUrl() ?>/about">About</a></li>
	<li><a href="<?= $this->serverUrl() ?>/services">Services</a></li>
	<li><a href="<?= $this->serverUrl() ?>/pricing">Pricing</a></li>
		<li><a href="<?= $this->serverUrl() ?>/contact">Contact</a></li>
		<li class="dropdown">
		<a href="<?= $this->serverUrl() ?>/#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
		<ul class="dropdown-menu">
				<li><a href="<?= $this->serverUrl() ?>/#">Action</a></li>
				<li><a href="<?= $this->serverUrl() ?>/#">Another action</a></li>
				<li><a href="<?= $this->serverUrl() ?>/#">Something else here</a></li>
				<li class="divider"></li>
				<li class="nav-header">Nav header</li>
				<li><a href="<?= $this->serverUrl() ?>/#">Separated link</a></li>
				<li><a href="<?= $this->serverUrl() ?>/#">One more separated link</a></li>
		</ul>
		</li>
</ul>
-->