<?php 
echo $this->navigation('navigation')->menu()
                                    ->setMinDepth(0)
                                    ->setMaxDepth(0);
?>
<!-- 
<ul id="footer-nav">
    <li><a href="<?= $this->serverUrl ?>/">Start</a></li>
    <li><a href="<?= $this->serverUrl ?>/about">About</a></li>
    <li><a href="<?= $this->serverUrl ?>/services">Services</a></li>
    <li><a href="<?= $this->serverUrl ?>/pricing">Pricing</a></li>
    <li><a href="<?= $this->serverUrl ?>/contact">Contact</a></li>
</ul>
 -->