        <!-- start: Flexslider -->
        <div class="slider">

            <div class="flexslider">
                <ul class="slides">

                    <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: list-item;" class="flex-active-slide">
                        <img src="./img/slider1.jpg" alt="">
                        <div class="slide-caption n hidden-phone">
                            <h3>This is a caption</h3>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                        </div>
                    </li>

                    <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: none;" class="">
                        <img src="./img/slider2.jpg" alt="">
                        <div class="slide-caption hidden-phone">
                            <h3>This is a caption</h3>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
                        </div>
                    </li>

                    <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: none;" class="">
                        <img src="./img/slider3.jpg" alt="">
                    </li>

                </ul>

                <ul class="flex-direction-nav">
                    <li><a class="flex-prev" href="<?= $this->serverUrl() ?>/#">Previous</a></li>
                    <li><a class="flex-next" href="<?= $this->serverUrl() ?>/#">Next</a></li>
                </ul>
                
            </div>
        </div>
        <!-- end: Flexslider -->