      <!-- start: Flexslider -->
      <div class="slider">
      
        <div class="flexslider">
          <ul class="slides">

            <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: list-item;" class="flex-active-slide">
              <img src="./img/slider1.jpg" alt="">
              <div class="slide-caption n hidden-phone">
                <h3>This is a caption</h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </p>
              </div>
            </li>

            <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: none;" class="">
              <img src="./img/slider2.jpg" alt="">
              <div class="slide-caption hidden-phone">
                <h3>This is a caption</h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </p>
              </div>
            </li>

            <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: none;" class="">
              <img src="./img/slider3.jpg" alt="">
            </li>

          </ul>

          <ul class="flex-direction-nav">
            <li><a class="flex-prev" href="<?= $this->serverUrl() ?>/#">Previous</a></li>
            <li><a class="flex-next" href="<?= $this->serverUrl() ?>/#">Next</a></li>
          </ul>
        </div>
      
      </div>
      <!-- end: Flexslider -->

          <!-- start: Hero Unit - Main hero unit for a primary marketing message or call to action -->
          <div class="hero-unit">
            <p>
          This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
        </p>
            <p><a class="btn btn-success btn-large">Learn more »</a></p>
          </div>
          <!-- end: Hero Unit -->

          <!-- start: Row -->
          <div class="row">
  
            <div class="span4">
                <div class="icons-box">
            <i class="ico-ok circle big"></i>
            <div class="title"><h3>Easy to use</h3></div>
            <p>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </p>
            <div class="clear"></div>
          </div>
            </div>

            <div class="span4">
                <div class="icons-box">
            <i class="ico-ipad circle big"></i>
            <div class="title"><h3>Responsive</h3></div>
            <p>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </p>
            <div class="clear"></div>
          </div>
            </div>

            <div class="span4">
                <div class="icons-box">
            <i class="ico-heart circle big"></i>
            <div class="title"><h3>User friendly</h3></div>
            <p>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </p>
            <div class="clear"></div>
          </div>
            </div>

          </div>
      <!-- end: Row -->
          
      <hr>
    
      <!-- start Clients List --> 
      <div class="clients-carousel">
        <div class="flex-viewport" style="overflow: hidden; position: relative;">
          <ul class="slides clients" style="width: 2000%; -webkit-transition: 0s; -webkit-transform: translate3d(-564px, 0, 0);">
            <li style="width: 147px; float: left; display: block;"><img src="./img/1.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/2.png" alt=""></li>  
            <li style="width: 147px; float: left; display: block;"><img src="./img/3.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/4.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/5.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/6.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/7.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/8.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/9.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/10.png" alt=""></li>   
          </ul>
        </div>
      </div>
      <!-- end Clients List -->
    
      <hr>
      
      <!-- start: Row -->
      <div class="row">
        
        <!-- start: Icon Boxes -->
        <div class="icons-box-vert-container">

          <!-- start: Icon Box Start -->
          <div class="span6">
            <div class="icons-box-vert">
              <i class="ico-ok ico-color circle-color big"></i>
              <div class="icons-box-vert-info">
                <h3>Easy to use</h3>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
              </div>
              <div class="clear"></div>
            </div>
          </div>
          <!-- end: Icon Box-->

          <!-- start: Icon Box Start -->
          <div class="span6">
            <div class="icons-box-vert">
              <i class="ico-cup  ico-white circle-color-full big-color"></i>
              <div class="icons-box-vert-info">
                <h3>Best choice</h3>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
              </div>
              <div class="clear"></div>
            </div>
          </div>
          <!-- end: Icon Box -->

        </div>
        <!-- end: Icon Boxes -->
        <div class="clear"></div>
      </div>
      <!-- end: Row -->