        <!--start: Container -->
        <div class="container">

            <!--start: Row -->
            <div class="row">
        
                <div class="span8">
                    
                    <!-- start: About Us -->
                    <div id="about">
                        <div class="title"><h3>About Us</h3></div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                    </div>  
                    <!-- end: About Us -->

                    <div class="horizontal-line"></div>

                    <!-- start: History -->
                    <div id="history">
                        <div class="title"><h3>History</h3></div>
                        <p>
                            <span class="dropcap">P</span>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <p>
                            <span class="dropcap color">P</span>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <p>
                            <span class="dropcap dark">P</span>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                        </p>
                    </div>  
                    <!-- end: History -->

                    <div class="horizontal-line"></div>

                    <!-- start: Team -->    
                    <div id="team">
                        
                        <div class="title"><h3>Team</h3></div>
                        
                        <!-- start: Row -->
                        <div class="row">
                        
                            <!-- start: About Member -->
                            <div class="span4">
                                <div class="avatar view-team">
                                    <img src="img/team_member.jpg" alt="team member">
                                    <div class="mask">
                                        <h2>About Me</h2>
                                        <p>
                                            As a freelance web developer with 7 years experience listening to clients needs and producing what they needed on time, I can help your presence online. I am most interested in finding problems that can and should be automated and developing eloquont solutions for them. 
                                        </p>
                                        <a href="#" class="info">My Personal Page</a>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="team-name">Brian Teachman <span> / Freelance Web Consultant</span></div>
                                <div class="social_profiles">
                                    <ul class="social-bookmarks">
                                        <li class="facebook"><a href="">facebook</a></li>
                                        <li class="flickr"><a href="">flickr</a></li>
                                        <li class="googleplus"><a href="#">googleplus</a></li>
                                        <li class="linkedin"><a href="#">linkedin</a></li>
                                        <li class="twitter"><a href="#">twitter</a></li>
                                        <li class="pinterest"><a href="#">pinterest</a></li>
                                    </ul>
                                </div>  
                            </div>
                            <!-- end: About Member -->

                            <!-- start: About Member -->
                            <div class="span4">
                                <div class="avatar view-team">
                                    <img src="img/team_member.jpg" alt="team member">
                                    <div class="mask">
                                        <h2>About Me</h2>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
                                        </p>
                                        <a href="#" class="info">My Personal Page</a>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="team-name">Lucas Luck <span> / Co-Founder, Project Manager</span></div>
                                <div class="social_profiles">
                                    <ul class="social-bookmarks">
                                        <li class="facebook"><a href="">facebook</a></li>
                                        <li class="flickr"><a href="">flickr</a></li>
                                        <li class="googleplus"><a href="#">googleplus</a></li>
                                        <li class="linkedin"><a href="#">linkedin</a></li>
                                        <li class="twitter"><a href="#">twitter</a></li>
                                        <li class="pinterest"><a href="#">pinterest</a></li>
                                    </ul>
                                </div>  
                            </div>
                            <!-- end: About Member -->  
                        
                        </div>
                        <!-- end: Row -->

                    </div>
                    <!-- end: Team -->
                    
                    
                </div>  
                
                <div class="span4">
                    
                    <!-- start: Sidebar -->
                    <div id="sidebar">

                        <!-- start: Skills -->
                        <div class="title"><h3>My Skills</h3></div>
                        <ul class="progress-bar">
                            <li>
                                <h5>Fathering ( 100% )</h5>
                                <div class="meter">
                                    <span style="width: 300px;"></span><!-- Edit width here -->
                                </div>
                            </li>
                            <li>
                                <h5>Application Development ( 80% )</h5>
                                <div class="meter">
                                    <span style="width: 240px;"></span><!-- Edit width here -->
                                </div>
                            </li>
                            <li>
                                <h5>Meditation ( 60% )</h5>
                                <div class="meter">
                                    <span style="width: 180px;"></span><!-- Edit width here -->
                                </div>
                            </li>
                            <li>
                                <h5>Wordpress ( 60% )</h5>
                                <div class="meter">
                                    <span style="width: 180px;"></span><!-- Edit width here -->
                                </div>
                            </li>
                            <li>
                                <h5>Martial Sudies ( 40% )</h5>
                                <div class="meter">
                                    <span style="width: 120px;"></span><!-- Edit width here -->
                                </div>
                            </li>
                        </ul>
                        <!-- end: Skills -->

                        <!-- start: Tabs -->
                        <div class="title"><h3>Tabs</h3></div>

                        <ul class="tabs-nav">
                            <li class="active"><a href="#tab1"><i class="mini-ico-glass"></i> Tab 1</a></li>
                            <li class=""><a href="#tab2"><i class="mini-ico-list"></i> Tab 2</a></li>
                            <li class=""><a href="#tab3"><i class="mini-ico-pencil"></i> Tab 3</a></li>
                        </ul>

                        <div class="tabs-container">
                            <div style="display: block;" class="tab-content" id="tab1">1. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                            <div style="display: none;" class="tab-content" id="tab2">2. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                            <div style="display: none;" class="tab-content" id="tab3">3. Lorem ipsum pharetra felis. Aliquam egestas consectetur elementum class aptent taciti sociosqu ad litora torquent perea conubia nostra lorem inceptos orem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                        </div>
                        <!-- end: Tabs -->

                        <!-- start: Testimonials-->

                        <div class="testimonial-container">

                            <div class="title"><h3>Testimonials</h3></div>

                                <div aria-live="polite" role="application" style="overflow: hidden; width: 100%;" class="testimonials-carousel" data-autorotate="3000"> <a href="#carousel-1-0" class="mr-rotato-next"></a> <a href="#carousel-1-0" class="mr-rotato-prev"></a>

                                    <ul aria-activedescendant="carousel-1-0-slide2" style="margin-left: -200%; float: left; width: 400%; transition: margin-left 0.3s ease 0s;" id="carousel-1-0" class="carousel">

                                        <li aria-hidden="true" id="carousel-1-0-slide0" role="tabpanel document" style="float: left; width: 25%;" class="testimonial">
                                            <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                            <div class="testimonials-bg"></div>
                                            <div class="testimonials-author">Lucas Luck, <span>CEO</span></div>
                                        </li>

                                        <li aria-hidden="true" id="carousel-1-0-slide1" role="tabpanel document" style="float: left; width: 25%;" class="testimonial">
                                            <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                            <div class="testimonials-bg"></div>
                                            <div class="testimonials-author">Lucas Luck, <span>CTO</span></div>
                                        </li>

                                        <li aria-hidden="false" id="carousel-1-0-slide2" role="tabpanel document" style="float: left; width: 25%;" class="testimonial mr-rotato-active-slide">
                                            <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                            <div class="testimonials-bg"></div>
                                            <div class="testimonials-author">Lucas Luck, <span>COO</span></div>
                                        </li>

                                        <li aria-hidden="true" id="carousel-1-0-slide3" role="tabpanel document" style="float: left; width: 25%;" class="testimonial">
                                            <div class="testimonials">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</div>
                                            <div class="testimonials-bg"></div>
                                            <div class="testimonials-author">Lucas Luck, <span>CMO</span></div>
                                        </li>

                                    </ul>

                                </div>

                            </div>

                        <!-- end: Testimonials-->

                    </div>
                    <!-- end: Sidebar -->
                    
                </div>
                
            </div>
            <!--end: Row-->
        </div>
        <!--end: Container -->