      <!-- start Clients List --> 
      <div class="clients-carousels">
        <div class="flex-viewport" style="overflow: hidden; position: relative;">
          <ul class="slides clients" style="width: 2000%; -webkit-transition: 0s; -webkit-transform: translate3d(-564px, 0, 0);">
            <li style="width: 147px; float: left; display: block;"><img src="./img/1.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/2.png" alt=""></li>  
            <li style="width: 147px; float: left; display: block;"><img src="./img/3.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/4.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/5.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/6.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/7.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/8.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/9.png" alt=""></li>
            <li style="width: 147px; float: left; display: block;"><img src="./img/10.png" alt=""></li>   
          </ul>
        </div>
      </div>
      <!-- end Clients List -->