<?php
$this->headTitle('Contact Me');
// $this->headLink()->prependStylesheet($this->basePath() . '');
// $this->headScript()->appendFile($this->basePath() . '');
$this->inlineScript()->appendFile('/js/commonmaputilgeocodermarker.js')
                     ->appendFile('/js/onion.js')
                     ->appendFile('/js/stats.js')
                     ->appendFile('/js/controls.js');

$form = $this->form;
$form->setAttribute('action', $this->url());
$form->prepare();

?>
        <!--start: Container -->
        <div class="container">

            <div class="row">
                <h2 class="span12">See if you can find the cat.</h2>
            </div>

            <!-- start: Map -->
            <div>
                <!-- starts: Google Maps -->
                <script type="text/javascript"
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBE-s3YKI3jr2ditYUfBiFHKknNR9gYaU&sensor=false">
                </script>
                <script type="text/javascript">

                    function initialize() {
                        var mapOptions = {
                            center: new google.maps.LatLng(48.770672, -122.417908),
                            zoom: 8,
                            mapTypeId: google.maps.MapTypeId.TERRAIN
                        };
                        var map = new google.maps.Map(
                            document.getElementById("map-canvas"),
                            mapOptions
                        );
                    }
                    google.maps.event.addDomListener(window, 'load', initialize);

                </script>
                <div id="map-canvas" class="google-map google-map-full map-canvas" style="height: 350px; margin-bottom: 20px; position: relative; background-color: rgb(229, 227, 223); overflow: hidden;"></div>
                <!-- end: Google Maps -->
            </div>

            <!-- end: Map -->   

        
            <!-- start: Contact Form -->
            <div class="span6">
                <div class="title">
                    <h4>If you need to contact me, here's a form!</h4>
                </div>

                <!-- start: Contact Form -->
                <div id="contact-form">
                    
                    <?= $this->form()->openTag($form) ?>
                        
                        <fieldset>
                            <div class="clearfix">
                                <label for="name"><span>Name:</span></label>
                                <div class="input">
                                    <?= $this->formRow($form->get('name')) ?>
                                </div>
                            </div>

                            <?php //$this->formRow($form->get('name')) ?>

                            <div class="clearfix">
                                <label for="email"><span>Email:</span></label>
                                <div class="input">
                                    <?= $this->formRow($form->get('email')) ?>
                                </div>
                            </div>

                            <div class="clearfix">
                                <label for="message"><span>Message:</span></label>
                                <div class="input">
                                    <?= $this->formRow($form->get('message')) ?>
                                </div>
                            </div>
                            
                            <div class="clearfix">
                                <?= $this->formRow($form->get('captcha')) ?>
                            </div>

                            <div class="actions">
                                <?= $this->formHidden($form->get('security')) ?>
                                <?= $this->formSubmit($form->get('send')) ?>
                            </div>
                        </fieldset>
                    
                    <?= $this->form()->closeTag($form) ?>
                    
                </div>
                <!-- end: Contact Form -->

            </div>
            <!-- end: Contact Form -->

            <!-- start: Social Sites --><!-- _social_sites_list.phtml --><!-- end: Social Sites -->

        </div>
        <!--end: Container -->