        <!--start: Container -->
        <div class="container">
            
            <!-- start: Row -->
            <div class="row">

                <div class="span4"></div>
    
                <div class="span8">
                    
                    <h1>frequently asked questions:</h1>

                    <h3>1. What is the total price of this project?</h3>

                    <blockquote>
                      
                    </blockquote>

                    <h3>2. How long will the project take?</h3>

                    <blockquote>
                      <p>It is hard to say. That depends on many variables such as the unique needs of problem/idea at hand, or the time it takes to get the materials needed from where ever they may be coming from, or many change request during the lifetime of the project.</p>
                    </blockquote>

                    <h3>3. What are your terms? <small>(all money up front? percentage down? installments?)</small></h3>

                    <blockquote>
                      <p>If less than $1000, payment upfront. Otherwise typically, 50% gets the project started, 25% upon design approval, the final 25% procures the release of the final product and materials, deployment (if applicable), and 1 hour of training  (again, if applicable).</p>
                    </blockquote>

                    <h3>4. Do you offer any financing options?</h3>

                    <blockquote>
                      <p>I do not provide loans for services provided as I am working here and need to feed my family. However, the fee schedule is flexible and under <em>most</em> circumstances projects can be completed in smaller peices that are completed as the budget permits.</p>
                    </blockquote>

                    <h3>5. Who owns my domain? <small>(if any)</small></h3>

                    <blockquote>
                      <p>If you already own it, then you do. If I purchase it for you during development, then ownership transfers upon final payment.</p>
                    </blockquote>

                    <h3>6. Who owns my website files, and databases? <small>(if any)</small></h3>

                    <blockquote>
                      
                    </blockquote>

                    <h3>7. How many total static (not dynamically-generated) pages are there?</h3>

                    <blockquote>
                      
                    </blockquote>

                    <h3>8. What are the functions my website makes available to my visitors?</h3>

                    <blockquote>
                      <p>Let's see... what did you have in mind? <a href="http://briant.me/contact">Contact me</a> and we'll discuss how we can meet your specific needs.</p>
                    </blockquote>

                    <h3>9. What are the admin functions my website makes available to me?</h3>

                    <blockquote>
                      <p>Not all websites are equal in form, function, or intention. That being said, all user operated web applications that I produce allow, at a minimum, the ability to access an administrative backend behind a log in form. Where the user can manage thier user details and update editable content throughout the site (what exactly that will be, will be discovered through client contact, a site survey, and a needs analysis). Some of the the CMS's that I use like <a href="">WordPress</a> and <a href="">SilverStripe</a>, provide much more functionality such as allowing other members to create an account and giving them roles and responsibilty, or adding module and plugins to extend functionality, and much more.</p>
                    </blockquote>

                    <h3>10. What can I alter without needing expert help?</h3>

                    <blockquote>
                      <p>That entirely depends on your understanding and skillset. During our Content Planning Meeting we will discuss area's of the site that need to be editable, typically refered to as editable content. Also metadata such as Site title and meta tags for the bots like keywords and description.</p>
                    </blockquote>

                    <h3>11. During the development process, who is my primary contact?</h3>

                    <blockquote>
                      <p>That'll be me, Brian Teachman.</p>
                    </blockquote>

                    <h3>12. How involved is my company in the development? Do we approve logos, mockups, etc.?</h3>

                    <blockquote>
                      <p>Absolutely! During the <a href="">Content Planning Meeting</a> I do my best to understand and visualize how you want what you want. Then, any digital assets provided by me, are to be signed off by you the client before being used in production.</p>
                    </blockquote>

                    <h3>13. Do you optimize our site for search engines? Is that included or extra?</h3>

                    <blockquote>
                      <p>The initial search engine optimisation at the Launch of the site is included in all my web development. Any optimisations or updates after site launch will be a new invoice or proposal for a <a href="">Marketing Campaign</a>.</p>
                    </blockquote>

                    <h3>14. Do you design or update my logo? Is that included or extra?</h3>

                    <blockquote>
                      <p>I do logo design/redesign, but it is extra.</p>
                    </blockquote>

                    <h3>15. Do you put the items in my store/catalog/database, or do you create the categories and give me the ability to create and edit products myself?</h3>

                    <blockquote>
                      <p>Either way, I do charge for it though. ;-)</p>
                    </blockquote>

                    <h3>16. What is your experience (design/programming/business management) that makes you capable of handling our project?</h3>

                    <blockquote>
                      
                    </blockquote>

                    <h3>17. How long have you been in business?</h3>

                    <blockquote>
                      
                    </blockquote>

                    <h3>18. What sets you apart from other website companies?</h3>

                    <blockquote>
                      
                    </blockquote>

                </div>

            </div>
            <!-- end: Row -->

            <!-- start: Hero Unit - Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <p>
                    <a href="/contact" class="btn btn-success btn-large">Contact Me »</a> We'll package up your idea!
                </p>
            </div>
            <!-- end: Hero Unit -->
        </div>
        <!--end: Container -->