<!-- start: Hero Unit - Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
    <p>I'm Brian Teachman and I do full stack web development and problem and process analysis. Anymore I am a father and a developing software architect. I seem to find myself hiking around the <a target="_blank" href="http://www.pnt.org/">Pacific Northwest National Scenic Trail</a> to clear my cache.</p>
    <p><!-- <a href="/services" class="btn btn-success btn-large">Learn more »</a> --></p>
</div>
<!-- end: Hero Unit -->

<!-- start: Row -->
<div class="row">

    <div class="span4">
        <div class="icons-box">
            <i class="ico-ok circle big"></i>
            <div class="title">
                <h3>Web Developer</h3>
            </div>
            <p>Architecting software for use over HTTP on both large screen and handheld media.</p>
            <div class="clear"></div>
        </div>
    </div>

    <div class="span4">
        <div class="icons-box">
            <i class="ico-ipad circle big"></i>
            <div class="title">
                <h3>Practioner</h3>
            </div>
            <p>An engaged father, life long student following my own interest, practioner of <a href="http://everydayzen.org/">Zen</a>.</p>
            <div class="clear"></div>
        </div>
    </div>

    <div class="span4">
        <div class="icons-box">
            <i class="ico-heart circle big"></i>
            <div class="title">
                <h3>Cartographer</h3>
            </div>
            <p>Finding your way can be eased when using highly readable, accurate maps.</p>
            <div class="clear"></div>
        </div>
    </div>

</div>
<!-- end: Row -->

<!-- <hr> -->

<!-- start: Row -->
<!-- <div class="row"> -->

    <!-- start: Icon Boxes -->
    <!-- <div class="icons-box-vert-container"> -->

        <!-- start: Icon Box Start -->
        <!-- <div class="span6">
            <div class="icons-box-vert">
                <i class="ico-ok ico-color circle-color big"></i>
                <div class="icons-box-vert-info">
                    <h3>Easy to use</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                </div>
                <div class="clear"></div>
            </div>
        </div> -->
        <!-- end: Icon Box-->

        <!-- start: Icon Box Start -->
        <!-- <div class="span6">
            <div class="icons-box-vert">
                <i class="ico-cup  ico-white circle-color-full big-color"></i>
                <div class="icons-box-vert-info">
                    <h3>Best choice</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                </div>
                <div class="clear"></div>
            </div>
        </div> -->
        <!-- end: Icon Box -->

    <!-- </div> -->
    <!-- end: Icon Boxes -->
<!--     <div class="clear"></div>
</div> -->
<!-- end: Row -->