        <!--start: Container -->
        <div class="container">
            
            <!-- start: Table -->
            <h4>Table ex. 1</h4>

            <div class="four-tables">

                <div class="pricing-table">
                    <div class="color-cccddd">
                        <h3>Standard</h3>
                        <h4><span class="price">€9.99</span> <span class="time">per month</span></h4>
                        <ul>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                        </ul>
                        <a href="#" class="buy"><span>Buy</span></a>
                    </div>
                </div>

                <div class="pricing-table">
                    <div class="color-666777">
                        <h3>Premium</h3>
                        <h4><span class="price">€29.99</span> <span class="time">per month</span></h4>
                        <ul>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                        </ul>
                        <a href="#" class="buy"><span>Buy</span></a>
                    </div>
                </div>

                <div class="pricing-table best-option">
                    <div class="color-custom">
                        <h3>Professional</h3>
                        <h4><span class="price">€49.99</span> <span class="time">per month</span></h4>
                        <ul>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                        </ul>
                        <a href="#" class="buy"><span>Buy</span></a>
                    </div>
                </div>

                <div class="pricing-table">
                    <div class="color-666777">
                        <h3>Ultimate</h3>
                        <h4><span class="price">€99.99</span> <span class="time">per month</span></h4>
                        <ul>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                        </ul>
                        <a href="#" class="buy"><span>Buy</span></a>
                    </div>
                </div>

            </div>
            <!-- end: Table -->



            <!-- start: Table -->
            <h4>Table ex. 2</h4>

            <div class="three-tables">

                <div class="pricing-table">
                    <div class="color-cccddd">
                        <h3>Standard</h3>
                        <h4><span class="price">€9.99</span> <span class="time">per month</span></h4>
                        <ul>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                        </ul>
                        <a href="#" class="buy"><span>Buy</span></a>
                    </div>
                </div>

                <div class="pricing-table best-option">
                    <div class="color-custom">
                        <h3>Premium</h3>
                        <h4><span class="price">€29.99</span> <span class="time">per month</span></h4>
                        <ul>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                        </ul>
                        <a href="#" class="buy"><span>Buy</span></a>
                    </div>
                </div>

                <div class="pricing-table">
                    <div class="color-666777">
                        <h3>Professional</h3>
                        <h4><span class="price">€49.99</span> <span class="time">per month</span></h4>
                        <ul>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                            <li>Custom option</li>
                        </ul>
                        <a href="#" class="buy"><span>Buy</span></a>
                    </div>
                </div>

            </div>
            <!-- end: Table -->

        </div>
        <!--end: Container -->