        <!--start: Container -->
        <div class="container">
            
            <!-- start: Row -->
            <div class="row">
    
                <div class="span4">
                    <div class="icons-box">
                        <i class="ico-iphone ico-color circle-color big"></i>
                        <div class="title"><h3>Strategy</h3></div>
                        <p title="He who best describes a problem, will best solve it. - ancient psalm">
                            What would you like to do? Who is it intened for? How do you want your data, how often? When do you want it done?
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>

                <div class="span4">
                    <div class="icons-box">
                        <i class="ico-imac circle big"></i>
                        <div class="title"><h3>Design</h3></div>
                        <p>
                            With the web constantly evolving, designing for flexibility makes it easier to face the constraints of the future.
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>

                <div class="span4">
                    <div class="icons-box">
                        <i class="ico-ok ico-white circle-color-full big-color"></i>
                        <div class="title"><h3>Responsive</h3></div>
                        <p>
                            Whether sitting at a desk in front of a monitor or looking up the closest bathroom while riding a bike down the middle of the road, your pages will look stunning.
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>

                <div class="span4">
                    <div class="icons-box">
                        <i class="ico-embed-close ico-color circle-color big"></i>
                        <div class="title"><h3>HTML5 &amp; CSS3</h3></div>
                        <p>
                            Using the latest technologies, we can do some <em>really neat things</em>.
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>

                <div class="span4">
                    <div class="icons-box">
                        <i class="ico-shopping-cart circle big"></i>
                        <div class="title"><h3>e-commerce</h3></div>
                        <p>
                            Offer your product or services online with flexible payments and easy to use shopping cart or a fully featured store-front.
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>

                <div class="span4">
                    <div class="icons-box">
                        <i class="ico-thumbs-up ico-white circle-color-full big-color"></i>
                        <div class="title"><h3>Social Marketing</h3></div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>

            </div>
            <!-- end: Row -->

            <!-- start: Hero Unit - Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <p>
                    <a href="/contact" class="btn btn-success btn-large">Contact Me »</a> We'll package up your idea!
                </p>
            </div>
            <!-- end: Hero Unit -->
        </div>
        <!--end: Container -->