<?php
// $this->headLink()->appendStylesheet($this->basePath() . '/css/faq.css');
?>
        <!--start: Container -->
        <div class="container">
            
            <!-- start: Row -->
            <div class="row">

                <div class="span12">

                    <h1>Brian Teachman <small>(the website)</small> Terms and Conditions <small>("Agreement")</small></h1>
                        
                    <p>This Agreement was last modified on September 19, 2013.</p>

                    <p>Please read these Terms and Conditions ("Agreement", "Terms and Conditions") carefully before using http://briant.me ("the Site") operated by Brian Teachman ("us", "we", or "our"). This Agreement sets forth the legally binding terms and conditions for your use of the Site at http://briant.me.</p>
                    <p>By accessing or using the Site in any manner, including, but not limited to, visiting or browsing the Site or contributing content or other materials to the Site, you agree to be bound by these Terms and Conditions. Capitalized terms are defined in this Agreement.</p>

                    <p><strong>Intellectual Property</strong><br />The Site and its original content, features and functionality are owned by Brian Teachman and are protected by international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.</p>

                    <p><strong>Termination</strong><br />We may terminate your access to the Site, without cause or notice, which may result in the forfeiture and destruction of all information associated with you. All provisions of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>

                    <p><strong>Links To Other Sites</strong><br />Our Site may contain links to third-party sites that are not owned or controlled by Brian Teachman.</p>
                    <p>Brian Teachman has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party sites or services. We strongly advise you to read the terms and conditions and privacy policy of any third-party site that you visit.</p>

                    <p><strong>Governing Law</strong><br />This Agreement (and any further rules, polices, or guidelines incorporated by reference) shall be governed and construed in accordance with the laws of Washington, United States, without giving effect to any principles of conflicts of law.</p>

                    <p><strong>Changes To This Agreement</strong><br />We reserve the right, at our sole discretion, to modify or replace these Terms and Conditions by posting the updated terms on the Site. Your continued use of the Site after any such changes constitutes your acceptance of the new Terms and Conditions.</p>
                    <p>Please review this Agreement periodically for changes. If you do not agree to any of this Agreement or any changes to this Agreement, do not use, access or continue to access the Site or discontinue any use of the Site immediately.</p>

                </div>

            </div>
            <!-- end: Row -->

            <!-- start: Hero Unit - Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <p>
                    If you have a more specific inquery or think of something I should add, please <a href="/contact" class="btn btn-success btn-large">contact me</a>
                </p>
            </div>
            <!-- end: Hero Unit -->

            <small style="color: #999;">Published and generated with permission from <a href="http://termsfeed.com/terms-conditions/generator/" style="color: #999; text-decoration: none;">www.termsfeed.com</a>.</small>

        </div>
        <!--end: Container -->